name: CI workflows
on: [push, pull_request]
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Use node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Main Dependencies
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: npm i

      - name: Install Sub Dependencies
        run: npm run bootstrap

      - name: Run ESLint
        run: npm run lint

  typescript:
    name: TypeScript Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Use node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Main Dependencies
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: npm i

      - name: Install Sub Dependencies
        run: npm run bootstrap

      - name: Run TSC
        run: npm run build

  tests:
    name: Jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Use node_modules cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Main Dependencies
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: npm i

      - name: Install Sub Dependencies
        run: npm run bootstrap

      - name: Run TSC
        run: npm run build

      - name: Run Jest
        run: npm run test